version: '3.5'

services:

  postgres:
    image: postgres:10.1
    container_name: postgres_1
    restart: unless-stopped
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - ${PROJECT_PATH}/postgresql:/var/lib/postgresql/data
      - ${PROJECT_PATH}/config:/etc/postgresql
    ports:
      - "5432:5432"


  pgadmin:
    image: dpage/pgadmin4
    environment:
     - "PGADMIN_DEFAULT_EMAIL=odoo@odoo.com" 
     - "PGADMIN_DEFAULT_PASSWORD=odoo" 
    links: 
      - postgres
    container_name: pgadmin4
    ports:
      - "80:80"

      

